# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: check that docs are up-to-date
          command: |
            . env/bin/activate
            PYTHONPATH=. python crew/cli.py docs
            if ! git diff --no-ext-diff --quiet --exit-code; then
                exit 1
            fi

      - run:
          name: run task tests
          command: |
            . env/bin/activate
            PYTHONPATH=. python crew/cli.py test

      - run:
          name: run unit tests
          command: |
            . env/bin/activate
            python -m unittest

      - run:
          name: check formatting
          command: |
            . env/bin/activate
            black --check crew tests

      - run:
          name: check flake
          command: |
            . env/bin/activate
            flake8 tests/**/*.py crew/**/*.py --ignore=E501,E203,W503

      - store_artifacts:
          path: test-reports
          destination: test-reports

  build_mac:
    macos:
      xcode: "10.0"

    #filters:  # using regex filters requires the entire branch to match
    #  branches:
    #    only:  # only branches matching the below regex filters will run
    #      - master

    working_directory: ~/repo

    steps:
      - run:
        name: build osx installer
        command: make build

workflows:
  version: 2
  test_build:
    jobs:
      - test
      - build_mac:
          requires:
            - test
