# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-development.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -e .

      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements-development.txt" }}

      - run:
          name: check that docs are up-to-date
          command: |
            . env/bin/activate
            PYTHONPATH=. python pitcrew/cli.py docs
            if ! git diff --no-ext-diff --quiet --exit-code; then
                exit 1
            fi

      - run:
          name: run task tests
          command: |
            . env/bin/activate
            PYTHONPATH=. python pitcrew/cli.py test

      - run:
          name: run unit tests
          command: |
            . env/bin/activate
            python -m unittest

      - run:
          name: check formatting
          command: |
            . env/bin/activate
            black --check pitcrew tests

      - run:
          name: check docs
          command: |
            . env/bin/activate
            crew docs --check

      - run:
          name: check flake
          command: |
            . env/bin/activate
            flake8 tests/**/*.py pit  crew/**/*.py --ignore=E501,E203,W503

      - store_artifacts:
          path: test-reports
          destination: test-reports
